### ISSUE TITLE
[python_llm]Feature/JH/갈등페이지 - RestAPI에서 보낸값을 받아 전처리

### ISSUE THREAD

**Issue by baejeonghyun23** [Team-A-I/otoo_python_llm#11]
## 💡 Feature Issue

- json형태로 보낸값들을 받아 필요한 값들을 파싱해서 추출해내는 전처리작업
- 필요한값 : 날짜 , 시간
- 제거해야할 문자 제거
## 🌿  To-do

- [ ] 데이터값 json형태로 잘받아오는지 확인
- [ ] 받아온 데이터에서 필요한값 파싱
- [ ] 필요없는 문자 제거
