### ISSUE TITLE
Feature/KH/OpenAI chat api 사용 환경 설정

### ISSUE THREAD

**Issue by heweun** [Team-A-I/otoo_python_llm#4]
## 💡 Feature Issue

- OpenAI chat api 사용 환경 설정
## 🌿  To-do

- [ ] api key 발급
- [ ] .env 파일 생성
- [ ] .gitignore 파일 생성
